dist: xenial
language: bash
if: head_branch =~ ^ft-automation-update$ OR branch = ft-automation

env:
  - tf_version=0.12.19 tf_init_cli_options="-input=false"

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

before_script:
  - chmod 775 ./before_deploy.sh && ./before_deploy.sh

jobs:
    include:
        - stage: terraform plan
          script:
              - cd ft/aws2azure/
              - echo "Validating Terraform fmt"
              - terraform fmt -recursive
              - echo "Pull request detected, creating change plan"
              - terraform init $tf_init_cli_options
              - terraform validate
              - pwd && ls -l
              - terraform plan -var-file="/usr/ec-file-transfer.tfvars"
              - terraform apply -var-file="/usr/ec-file-transfer.tfvars" -auto-approve
              - sleep 540
              - terraform destroy -var-file="/usr/ec-file-transfer.tfvars" -auto-approve

notifications:
  email:
    recipients:
    - ec-research@ge.com
    on_success: always
    on_failure: always